branch-defaults:
  main:
    environment: cryptoflask-demo-env
global:
  application_name: cryptoflask-demo
  branch: null
  default_ec2_keyname: aws-cryptoapp-demo
  default_platform: Python 3.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
